spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    username: tiger
    url: jdbc:oracle:thin:@localhost:1521:orcl
    type: oracle.ucp.jdbc.PoolDataSourceImpl
    password: root
